m4-t1 implementing api
htmlacademy-nodejs/1486707-typoteka-3 pull request #10
Opened 2022-05-03 09:29 UTC by vladn255

2022-05-03 18:32 UTC, html-malex requested changes

2022-05-03 18:32 UTC, html-malex commented on src/service/api/search.js
> +      res.status(HttpCode.BAD_REQUEST).json([]);
Не совсем уверен, что это Bad Request. Держи в уме, что коды ошибок - это коды от _сервера_, а не от API. Вполне может быть ситуация, когда ты ищешь именно по пустому значению (пустой строке)

2022-05-03 18:32 UTC, html-malex commented on src/service/api/index.js
> +(async () => {
Не совсем понял конструкцию - какова ее цель?

2022-05-03 18:32 UTC, html-malex commented on src/service/api/search.js
> +    const searchStatus = searchResults.length ? HttpCode.OK : HttpCode.NOT_FOUND;
Аналогично, 404 - это не ошибка при поиске. Предлагаю тут возвращать 200, но пустое тело

2022-05-03 18:32 UTC, html-malex commented on src/service/middlewares/articleValidator.js
> +    res.status(HttpCode.BAD_REQUEST).send(`Bad request`);
При ошибках валидации обычно присылают 422 код

2022-05-04 15:51 UTC, vladn255 commented on src/service/api/index.js
> +(async () => {
Так сделано, чтобы не создавать отдельную функцию и вызывать её следом. То есть, вместо конструкции вида:
const foo = async () => { await ... };
foo();
Мы сразу создаём и вызываем функцию. Внутренности этой функции сначала достают моковые данные, а затем создают API на их основе.

2022-05-04 15:52 UTC, vladn255 commented on src/service/api/search.js
> +    const searchStatus = searchResults.length ? HttpCode.OK : HttpCode.NOT_FOUND;
Принято, поправил.

2022-05-04 15:53 UTC, vladn255 commented on src/service/middlewares/articleExists.js
> +    return res.status(HttpCode.NOT_FOUND).send(`Article with the ${articleId} id not found`);
Согласен, увлёкся немного)) Поправил

2022-05-04 15:59 UTC, vladn255 commented on src/service/middlewares/articleValidator.js
> +    res.status(HttpCode.BAD_REQUEST).send(`Bad request`);
Можно и 422 код сделать, но если посмотреть документацию MDN ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422 ), то 422 код немного про другое. Или я не туда смотрю? Во всяком случае, в примере для аналогичного случая использовали 400 код. Не факт, что авторы курса здесь правы, конечно, но условный "заказчик" в этом случае скорее всего захочет увидеть 400, поэтому оставил пока))

2022-05-04 18:43 UTC, html-malex commented on src/service/api/index.js
> +(async () => {
Если бы она была синхронная, то проблем особо нет, но она у тебя async. Т.е. она не будет выполнена при переходе к следующей команде - только будет добавлена в event loop. Поэтому так лучше не делать. Вдруг где-то далее по программе должен будет использоваться результат исполнения этой функции, а она еще не завершилась - это может привести к самым "бесячим" ошибкам: при одном запуске все работает как надо, а при другом падает. Отлавливать и отлаживать их ой как нелегко

Если же изначальная идея такая и была ("запустить и забыть"), то все равно лучше вынести ее в отдельную async-функцию, экспортировать из модуля и вызвать в том месте, где это нужно (не забыв при этом указать await). Добро пожаловать в асинхронное программирование :)

2022-05-04 18:53 UTC, html-malex commented on src/service/middlewares/articleValidator.js
> +    res.status(HttpCode.BAD_REQUEST).send(`Bad request`);
400 код - это из серии "что-то пошло не так", а тут вполне понятно, _что_ пошло не так :) Ошибки валидации - это вполне ожидаемые ошибки (хоть и ошибки)

Читаем по указанной тобой ссылке
```
response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions
```
Вольный перевод:
```
У сервера нет вопросов к запросу, но приложение не может обработать его
```

Окей, я отмечу тред как resolved и оставлю на твое усмотрение, какой код использовать (400 или 422). Ибо тут нет единого общепринятого мнения

2022-05-05 14:29 UTC, vladn255 commented on src/service/api/index.js
> +(async () => {
Понял, принял, осознал))

2022-05-06 22:29 UTC, html-malex approved these changes

2022-05-06 22:29 UTC, merged