Module4 task2
htmlacademy-nodejs/1486707-typoteka-3 pull request #11
Opened 2022-05-07 06:32 UTC by vladn255

2022-05-08 23:18 UTC, html-malex requested changes

2022-05-08 23:18 UTC, html-malex commented on src/constants.js
> +module.exports.Env = {
Уже [все придумано](https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production) за нас :)

2022-05-08 23:18 UTC, html-malex commented on src/service/api/articles.e2e.test.js
> +  beforeAll(async () => {
Мой совет - не делай так. И вообще старайся крайне осторожно использовать всякие `before` и `after` в тестах, только по необходимости. Почему?
- главное правило теста - максимальная автономность, без side-эффектов и внешних зависимостей. Все то, что старательно избегается в "нормальном" программировании, в тестах - норма: повторяющаяся копипаста, константы и хардкорно забитые переменные и т.д.
- если у тебя отваливается выполнение `beforeAll` - это может быть как ошибкой теста, так и ошибкой окружения, сети, компа и т.д. А это неправильно.

Как бы я рекомендовал писать тесты
```
test(`Status code 200`, async () => {
   const response = await request(app).get(`/articles`);
   expect(response.statusCode).toBe(HttpCode.OK);
});
```
Что мы здесь получаем
- тест максимально автономен, все что ему нужно - внутри самого теста
- сразу по коду виден весь сценарий теста: делаем такой-то запрос, получаем ответ, проверяем его
- тест можно запустить в IDE, не опасаясь (ну почти), что где-то снаружи что-то не проинициализировали (попробуй найти сам, что осталось вне теста)

Тестирование (особенно написание unit-тестов, которые пишет сам разработчик) - это мега-важная вещь в разработке более-менее крупных проектов (рекомендую почитать про пирамиду тестирования)

2022-05-08 23:18 UTC, html-malex commented on src/service/lib/logger.js
> +const isDevMode = process.env.NODE_LEVEL === Env.DEVELOPMENT;
проверяй лучше значение `NODE_ENV`

2022-05-09 13:35 UTC, vladn255 commented on src/constants.js
> +module.exports.Env = {
Согласен, отдельно назначать переменные для типовых 'development' и 'production' кажется излишним. Так понимаю, в данном случае переменные им присваиваем, чтобы не было "магических" значений и строк в коде. Исход из этого, думаю, можно оставить эти константы, чтобы соблюсти требования к выполнению проекта. Или я не понял смысла замечания?)

2022-05-09 13:35 UTC, vladn255 commented on src/service/lib/logger.js
> +const isDevMode = process.env.NODE_LEVEL === Env.DEVELOPMENT;
Согласен, поправил.

2022-05-10 16:08 UTC, html-malex commented on src/constants.js
> +module.exports.Env = {
Конкретно в этом случае создание переменных излишне, ибо про `NODE_ENV` есть [упоминание](https://nodejs.org/ru/docs/guides/simple-profiling/) в официальной документации по Node.js. Эта переменная используется практически в каждом проекте

2022-05-12 09:00 UTC, vladn255 commented on src/constants.js
> +module.exports.Env = {
Принято, поправил

2022-05-12 09:02 UTC, vladn255 commented
Сейчас валятся тесты comments и articles. Попробовал в articles создать столько переменных для инстансов, сколько можно, но всё равно тест по добавлению статьи влияет на тест по удалению статьи (с ними пока вожусь).

2022-05-17 17:49 UTC, html-malex approved these changes

2022-05-17 17:49 UTC, merged