m5-t1
htmlacademy-nodejs/1486707-typoteka-3 pull request #13
Opened 2022-05-27 08:51 UTC by vladn255

2022-05-27 17:20 UTC, html-malex requested changes

2022-05-27 17:20 UTC, html-malex commented on src/schema.sql
> +    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
Поскольку у нас используется Postgres, то рекомендую смотреть в сторону [SERIAL](https://www.postgresql.org/docs/current/datatype-numeric.html) для primary-ключей. Подробнее [тут](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-serial/)

2022-05-27 17:20 UTC, html-malex commented on src/schema.sql
> +    name varchar(30) NOT NULL
Забудь про VARCHAR и используй везде просто [TEXT](https://www.postgresql.org/docs/14/datatype-character.html). Оставляю в качестве "домашнего задания" погуглить холивары на предмет быстродействия TEXT vs VARCHAR в Postgres :)

2022-05-30 15:13 UTC, vladn255 commented on src/schema.sql
> +    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
Принято, поправил. Так понимаю, конструкция GENERATED ALWAYS AS IDENTITY мало отличается от SERIAL кроме того, что защищает поле от перезаписи пользователем ( https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/ ), поэтому разницы большой не увидел)) Но если SERIAL более распространен на практике, то можно остановиться на нём.

2022-05-30 15:13 UTC, vladn255 commented on src/schema.sql
> +    name varchar(30) NOT NULL
Ох уж эти холивары))) Принято - поменял на TEXT везде)

2022-05-30 18:30 UTC, html-malex commented on src/schema.sql
> +    name varchar(30) NOT NULL
И на фронте, и на бэке. Валидация данных - это НЕ зона ответственности БД

2022-05-30 18:31 UTC, merged